language: node_js
node_js:
  - "11"
# Don't build branches, only on PR
branches:
  only:
  - master
before_script:
- export TZ=Europe/Berlin
- npm i typescript tslint -g
notifications:
  email:
    on_failure: change
